// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enableAutomaticSearch': string;
  'enableInteractiveSearch': string;
  'enableRss': string;
  'errorsLink': string;
  'implementation': string;
  'name': string;
  'priority': string;
  'statistics': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
