// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'completed': string;
  'container': string;
  'errorMessage': string;
  'failed': string;
  'header': string;
  'indexerList': string;
  'indexerName': string;
  'indexerStatus': string;
  'progress': string;
  'resultCount': string;
  'searching': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
