// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMessage': string;
  'errorType': string;
  'httpStatusCode': string;
  'operationType': string;
  'timestamp': string;
}
export const cssExports: CssExports;
export default cssExports;
