// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakdown': string;
  'breakdownItem': string;
  'breakdownList': string;
  'failureCount': string;
  'header': string;
  'operationDetails': string;
  'operationHeader': string;
  'operationName': string;
  'operationRate': string;
  'statItem': string;
  'statLabel': string;
  'statValue': string;
  'statistics': string;
  'successCount': string;
  'totalCount': string;
}
export const cssExports: CssExports;
export default cssExports;
