// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'importSearches__items': string;
  'importSearches__itemsTable': string;
  'importSearches__jobRow': string;
  'importSearches__jobs': string;
  'importSearches__layout': string;
  'importSearches__upload': string;
  'isActive': string;
}
export const cssExports: CssExports;
export default cssExports;
